#!/bin/bash
# ------------------------------Question 4------------------------------------
#  Write a program called drivingSpeed to ask user for a number between 
#  1 and 120.
#
#  If the given number is greater than the speed limit of 70, the program 
#  should say how many miles above the speed limit. And if it's less than 70, 
#  show how many miles less than the speed limit.
# ----------------------------------------------------------------------------

speedLimit=70
calculateSpeed=0

echo "The posted speed limit is $speedLimit"
echo "Enter a speed between 1 and 120"
echo -n "> "
read inputSpeed
if [ $inputSpeed -ge $speedLimit ]
then
	if [ $inputSpeed -eq $speedLimit ]
	then
		echo "$inputSpeed is the same as the $speedLimit"
	else
		let calculateSpeed=$inputSpeed-$speedLimit
		echo "$inputSpeed is $calculateSpeed over the speed limit of $speedLimit"
	fi
else
	let calculateSpeed=$speedLimit-$inputSpeed
	echo "$inputSpeed is $calculateSpeed under the speed limit of $speedLimit"
fi


