#!/bin/bash
# ---------------------------------Question 3---------------------------------
#  Using a for loop and only mutiplication operator, write a program to take 
#  two numbers from the user and show the result of the first number to the 
#  power of the second number.
# ----------------------------------------------------------------------------


total=1

echo "--------------------------------"
echo -n "      Give me a number: "
read firstNum
echo -n "Give me another number: "
read secondNum
echo  "--------------------------------"
for i in `seq 1 $secondNum`
do
	let total=$total*$firstNum
done
echo "$firstNum to the power of $secondNum is $total"
